package main

import (
	"fmt"
	"strings"
)

func generateBotInterface(d APIDescription) error {
	file := strings.Builder{}
	file.WriteString(`
// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package gotgbot

import (
	"context"
	"encoding/json"
)

`)

	file.WriteString("type Bot interface {")
	file.WriteString(`
// Essential methods to perform HTTP requests
// POST request to the bot API.
Post(method string, params map[string]string, data map[string]NamedReader, opts *RequestOpts) (json.RawMessage, error)
// POST request to the bot API, with a context.
PostWithContext(ctx context.Context, method string, params map[string]string, data map[string]NamedReader, opts *RequestOpts) (json.RawMessage, error)
// Get the current bot details - usually obtained by a GetMe() at bot instantiation.
Me() User

// Generated API methods`)
	for _, tgMethodName := range orderedMethods(d) {
		tgMethod := d.Methods[tgMethodName]

		signature, _, _, err := generateMethodSignature(d, tgMethod)
		if err != nil {
			return fmt.Errorf("failed to generate bot interface for %s: %w", tgMethodName, err)
		}

		file.WriteString("\n" + signature)
	}
	file.WriteString("}")

	return writeGenToFile(file, "gen_bot_interface.go")
}
