package main

import (
	"errors"
	"fmt"
	"regexp"
	"strings"
)

func generateConsts(d APIDescription) error {
	consts := strings.Builder{}
	consts.WriteString(`
// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package gotgbot

`)

	updateConsts, err := generateUpdateTypeConsts(d)
	if err != nil {
		return fmt.Errorf("failed to generate consts for update types: %w", err)
	}
	consts.WriteString(updateConsts)

	chatActions, err := generateChatActionConsts(d)
	if err != nil {
		return fmt.Errorf("failed to generate consts for chat actions: %w", err)
	}
	consts.WriteString(chatActions)

	stickerTypeConsts, err := generateTypeConsts(d, "Sticker")
	if err != nil {
		return fmt.Errorf("failed to generate consts for sticker types: %w", err)
	}
	consts.WriteString(stickerTypeConsts)

	chatTypeConsts, err := generateTypeConsts(d, "Chat")
	if err != nil {
		return fmt.Errorf("failed to generate consts for chat types: %w", err)
	}
	consts.WriteString(chatTypeConsts)

	buttonStyleConsts, err := generateButtonStyleConsts(d)
	if err != nil {
		return fmt.Errorf("failed to generate consts for button styles: %w", err)
	}
	consts.WriteString(buttonStyleConsts)

	msgEntConsts, err := generateTypeConsts(d, "MessageEntity")
	if err != nil {
		return fmt.Errorf("failed to generate consts for MessageEntity types: %w", err)
	}
	consts.WriteString(msgEntConsts)

	for _, t := range orderedTgTypes(d) {
		if len(d.Types[t].Subtypes) == 0 {
			continue
		}

		typeName := "type"
		switch t {
		case "ChatBoostSource", "PassportElementError":
			typeName = "source"
		case "ChatMember":
			typeName = "status"
		case "InputMessageContent", "MaybeInaccessibleMessage":
			continue // SKIP!
		}

		interfConsts, err := generateQuotedTypeFields(d, t, typeName)
		if err != nil {
			return fmt.Errorf("failed to generate consts for %s types: %w", t, err)
		}
		consts.WriteString(interfConsts)
	}

	return writeGenToFile(consts, "gen_consts.go")
}

func generateQuotedTypeFields(d APIDescription, interfaceName string, constantName string) (string, error) {
	interfaceType, ok := d.Types[interfaceName]
	if !ok {
		return "", errors.New("interface not found")
	}

	consts := make([]string, 0, len(interfaceType.Subtypes))
	for _, subT := range interfaceType.Subtypes {
		t, ok := d.Types[subT]
		if !ok {
			if subT == tgTypeString {
				consts = append(consts, writeConst(ConstantName(interfaceName, constantName, tgTypeString), strings.ToLower(tgTypeString)))
				continue
			} else if subT == "Array of RichText" {
				continue
			}

			return "", fmt.Errorf("subtype %s not found", subT)
		}

		tName, err := t.getTypeNameFromParent(constantName)
		if err != nil {
			return "", fmt.Errorf("failed to get type name for subtype %s: %w", subT, err)
		}
		consts = append(consts, writeConst(ConstantName(interfaceName, constantName, tName), strings.ToLower(tName)))
	}

	out := strings.Builder{}
	out.WriteString(fmt.Sprintf("\n// The consts listed below represent all the %s types.", interfaceName))
	out.WriteString("\nconst (")
	out.WriteString(strings.Join(unique(consts...), ""))
	out.WriteString(")\n\n")

	return out.String(), nil
}

func generateUpdateTypeConsts(d APIDescription) (string, error) {
	updType, ok := d.Types["Update"]
	if !ok {
		return "", errors.New("missing 'Update' type data")
	}
	out := strings.Builder{}
	// First we generate the consts
	out.WriteString("\n// The consts listed below represent all the update types that can be requested from telegram.")
	out.WriteString("\nconst (")
	for _, f := range updType.Fields {
		if f.Required {
			// All the update types are optional, so skip required values.
			continue
		}
		out.WriteString(writeConst("UpdateType"+snakeToTitle(f.Name), f.Name))
	}
	out.WriteString(")\n")

	// Then we generate the helper for the update kind logic
	out.WriteString("\n// GetType is a helper method to easily identify the type of update that is being received.")
	out.WriteString("\nfunc (u Update) GetType() string {")
	out.WriteString("\nswitch {")
	for _, f := range updType.Fields {
		if f.Required {
			// All the update types are optional, so skip required values.
			continue
		}
		out.WriteString(fmt.Sprintf("\ncase u.%s != nil:", snakeToTitle(f.Name)))
		out.WriteString("\nreturn UpdateType" + snakeToTitle(f.Name) + "\n")
	}

	out.WriteString("\ndefault:")
	out.WriteString("\nreturn \"unknown\"")
	out.WriteString("\n}")
	out.WriteString("\n}")
	return out.String(), nil
}

func generateTypeConsts(d APIDescription, typeName string) (string, error) {
	updType, ok := d.Types[typeName]
	if !ok {
		return "", errors.New("missing '" + typeName + "' type data")
	}
	out := strings.Builder{}
	out.WriteString("\n// The consts listed below represent all the " + strings.ToLower(typeName) + " types that can be obtained from telegram.")
	out.WriteString("\nconst (")

	types, err := getFieldQuotes(updType, "type")
	if err != nil {
		return "", fmt.Errorf("failed to get field quotes from %s: %w", typeName, err)
	}

	for _, t := range types {
		out.WriteString(writeConst(typeName+"Type"+snakeToTitle(t), t))
	}

	out.WriteString(")\n\n")
	return out.String(), nil
}

func generateButtonStyleConsts(d APIDescription) (string, error) {
	keybType, ok := d.Types["KeyboardButton"]
	if !ok {
		return "", errors.New("missing KeyboardButton type data")
	}
	out := strings.Builder{}
	out.WriteString("\n// The consts listed below represent all the KeyboardButton styles that can be sent.")
	out.WriteString("\nconst (")

	types, err := getFieldQuotes(keybType, "style")
	if err != nil {
		return "", fmt.Errorf("failed to get keyboard types: %w", err)
	}

	for _, t := range types {
		out.WriteString(writeConst("KeyboardButtonStyle"+snakeToTitle(t), t))
	}

	out.WriteString(")\n\n")
	return out.String(), nil
}

func getFieldQuotes(updType TypeDescription, fieldName string) ([]string, error) {
	for _, f := range updType.Fields {
		if f.Name != fieldName {
			// the field we want to look at is called "type", ignore all others.
			continue
		}
		types, err := extractQuotedValues(f.Description)
		if err != nil {
			return nil, fmt.Errorf("failed to get quoted values: %w", err)
		}
		return types, nil
	}

	return nil, fmt.Errorf("field '%s' not found", fieldName)
}

func generateChatActionConsts(d APIDescription) (string, error) {
	methodName := "sendChatAction"
	fieldName := "action"

	sendChatActionMethod, ok := d.Methods[methodName]
	if !ok {
		return "", errors.New("missing '" + methodName + "' method data")
	}

	var description string

	for _, field := range sendChatActionMethod.Fields {
		if field.Name == fieldName {
			description = field.Description

			break
		}
	}

	if description == "" {
		return "", errors.New("missing '" + fieldName + "' method field")
	}

	// Parse chat action from the description
	var chatActions []string

	re := regexp.MustCompile(`(?P<action>[a-z_]+) f?or`)
	results := re.FindAllStringSubmatch(description, -1)

	for _, result := range results {
		chatActions = append(chatActions, result[1])
	}

	out := strings.Builder{}
	out.WriteString("\n// The consts listed below represent all the chat action options that can be sent to telegram.")
	out.WriteString("\nconst (")

	for _, a := range chatActions {
		constName := "ChatAction" + snakeToTitle(a)
		out.WriteString(writeConst(constName, a))
	}

	out.WriteString(")\n\n")

	return out.String(), nil
}

func writeConst(name string, value string) string {
	return fmt.Sprintf("\n%s = \"%s\"", name, value)
}
