package main

import (
	"fmt"
	"sort"
	"strings"
)

func generateMethods(d APIDescription) error {
	file := strings.Builder{}
	file.WriteString(`
// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package gen
import (
	urlLib "net/url" // renamed to avoid clashes with url vars
	"encoding/json"
	"strconv"
	"fmt"
	"io"
)
`)

	// TODO: Obtain ordered map to retain tg ordering
	var methods []string
	for k := range d.Methods {
		methods = append(methods, k)
	}
	sort.Strings(methods)

	for _, tgMethodName := range methods {
		tgMethod := d.Methods[tgMethodName]
		file.WriteString(generateMethodDef(d, tgMethod, tgMethodName))
	}

	return writeGenToFile(file, "gen/gen_methods.go")
}

func generateMethodDef(d APIDescription, tgMethod MethodDescription, tgMethodName string) string {
	method := strings.Builder{}

	// defaulting to [0] is ok because its either message or bool
	retType := toGoTypes(tgMethod.Returns[0])
	if isTgType(d.Types, retType) {
		retType = "*" + retType
	}
	defaultRetVal := getDefaultReturnVal(retType)

	args, optionalsStruct := getArgs(tgMethodName, tgMethod)
	if optionalsStruct != "" {
		method.WriteString("\n" + optionalsStruct)
	}

	for _, d := range tgMethod.Description {
		method.WriteString("\n// " + d)
	}
	method.WriteString("\n// " + tgMethod.Href)

	method.WriteString("\nfunc (bot Bot) " + strings.Title(tgMethodName) + "(" + args + ") (" + retType + ", error) {")
	method.WriteString("\n	v := urlLib.Values{}")

	valueGen, hasData := methodArgsToValues(tgMethod, defaultRetVal)
	method.WriteString(valueGen)

	method.WriteString("\n")

	if hasData {
		method.WriteString("\nr, err := bot.Post(\"" + tgMethodName + "\", v, data)")
	} else {
		method.WriteString("\nr, err := bot.Get(\"" + tgMethodName + "\", v)")
	}
	method.WriteString("\n	if err != nil {")
	method.WriteString("\n		return " + defaultRetVal + ", err")
	method.WriteString("\n	}")
	method.WriteString("\n")

	retVarType := retType
	retVarName := getRetVarName(retVarType)
	isPointer := strings.HasPrefix(retVarType, "*")
	addr := ""
	if isPointer {
		retVarType = strings.TrimLeft(retVarType, "*")
		addr = "&"
	}
	method.WriteString("\nvar " + retVarName + " " + retVarType)
	method.WriteString("\nreturn " + addr + retVarName + ", json.Unmarshal(r, &" + retVarName + ")")
	method.WriteString("\n}")

	return method.String()
}

func methodArgsToValues(method MethodDescription, defaultRetVal string) (string, bool) {
	hasData := false
	bd := strings.Builder{}
	for _, f := range method.Fields {
		goParam := snakeToCamel(f.Parameter)
		if !isRequiredField(f) {
			goParam = "opts." + snakeToTitle(f.Parameter)
		}

		// TODO: more than one type
		converter := goTypeToString(toGoTypes(f.Types[0]))
		if converter == "" {
			if f.Types[0] == "InputFile" {
				// TODO: support case where its just inputfile and not string

				hasData = true
				bd.WriteString("\nif " + goParam + "!= nil {")
				bd.WriteString("\n	if s, ok := " + goParam + ".(string); ok {")
				bd.WriteString("\n		v.Add(\"" + f.Parameter + "\", s)")
				bd.WriteString("\n	} else if r, ok := " + goParam + ".(io.Reader); ok {")
				bd.WriteString("\n		v.Add(\"" + f.Parameter + "\", \"attach://" + f.Parameter + "\")")
				bd.WriteString("\n		data[\"" + f.Parameter + "\"] = NamedReader{File: r}")
				bd.WriteString("\n	} else if nf, ok := " + goParam + ".(NamedReader); ok {")
				bd.WriteString("\n		v.Add(\"" + f.Parameter + "\", \"attach://" + f.Parameter + "\")")
				bd.WriteString("\n		data[\"" + f.Parameter + "\"] = nf")
				bd.WriteString("\n	} else {")
				bd.WriteString("\n		return " + defaultRetVal + ", fmt.Errorf(\"unknown type for InputFile: %T\"," + goParam + ")")
				bd.WriteString("\n	}")
				bd.WriteString("\n}")
			} else if strings.HasPrefix(f.Types[0], "Input") {
				// TODO: Add InputMedia support; use interfaces
				fmt.Println("Purposefully skipping unhandled file item to allow for later data logic", f.Types)
				continue
			}

			// dont use goParam since that contains the `opts.` section
			bytesVarName := snakeToCamel(f.Parameter) + "Bs"
			if isTgArray(f.Types[0]) {
				bd.WriteString("\nif " + goParam + " != nil {")
			}

			bd.WriteString("\n	" + bytesVarName + ", err := json.Marshal(" + goParam + ")")
			bd.WriteString("\n	if err != nil {")
			bd.WriteString("\n		return " + defaultRetVal + ", fmt.Errorf(\"failed to marshal " + f.Parameter + ": %w\", err)")
			bd.WriteString("\n	}")
			bd.WriteString("\n	v.Add(\"" + f.Parameter + "\", string(" + bytesVarName + "))")

			if isTgArray(f.Types[0]) {
				bd.WriteString("\n}")
			}
		} else {
			bd.WriteString("\nv.Add(\"" + f.Parameter + "\", " + fmt.Sprintf(converter, goParam) + ")")
		}
	}

	if hasData {
		return "\ndata := map[string]NamedReader{}" + bd.String(), hasData
	}

	return bd.String(), hasData
}

func getRetVarName(retType string) string {
	for strings.HasPrefix(retType, "*") {
		retType = strings.TrimPrefix(retType, "*")
	}
	for strings.HasPrefix(retType, "[]") {
		retType = strings.TrimPrefix(retType, "[]")
	}
	return strings.ToLower(retType[:1])
}

func getArgs(name string, method MethodDescription) (string, string) {
	var requiredArgs []string
	var optionalArgs []MethodFields
	for _, f := range method.Fields {
		if isRequiredField(f) {
			// TODO: Not just assume first type
			requiredArgs = append(requiredArgs, fmt.Sprintf("%s %s", snakeToCamel(f.Parameter), toGoTypes(f.Types[0])))
			continue
		}
		optionalArgs = append(optionalArgs, f)
	}
	optionalsStruct := ""
	if len(optionalArgs) > 0 {
		optionalsName := snakeToTitle(name) + "Opts"
		bd := strings.Builder{}
		bd.WriteString("\ntype " + optionalsName + " struct {")
		for _, opt := range optionalArgs {
			bd.WriteString("\n// " + opt.Description)
			bd.WriteString("\n" + fmt.Sprintf("%s %s", snakeToTitle(opt.Parameter), toGoTypes(opt.Types[0])))
		}
		bd.WriteString("\n}")
		optionalsStruct = bd.String()

		requiredArgs = append(requiredArgs, fmt.Sprintf("opts %s", optionalsName))
	}

	return strings.Join(requiredArgs, ", "), optionalsStruct
}

func isRequiredField(f MethodFields) bool {
	return f.Required == "Yes"
}
